#if INTELMOTE2_CONTRIB_DIR is not defined, see stanford-lgl/README file
COMPONENT=cameraJpegTestC

PFLAGS += -I$(INTELMOTE2_CONTRIB_DIR)/support/sdk/c/compress
PFLAGS += -I$(INTELMOTE2_CONTRIB_DIR)/tos/lib/BigMsg
CFLAGS += -DPXA27X_FREQ=208
#CFLAGS += -Wcast-align -Wpadded -Wpacked
include ../Makerules