#!/usr/bin/env python

# This is a quick and dirty example of how to use the MoteIF interface in
# Python

from TestSerialMsg import *
from tinyos.message import MoteIF

class MyClass:
    def __init__(self):
        # Create a MoteIF
        self.mif = MoteIF.MoteIF()
        # Attach a source to it
        self.source = self.mif.addSource("sf@localhost:9001")

        # SomeMessageClass.py would be generated by MIG
        self.mif.addListener(self, TestSerialMsg)

    # Called by the MoteIF's receive thread when a new message
    # is received
    def receive(self, src, msg):
        print "Received message: "+ str(msg)

if __name__ == "__main__":
    m = MyClass()
