DRIVER_OBJS=build/micaz/c-sf.o build/micaz/sf.o build/micaz/tossim.o build/micaz/c-support.o build/micaz/sim.o build/micaz/pytossim.o build/micaz/throttle.o 

SFDIR=$(TOSCONTRIB)/csm/tos/lib/tossim

all:
	make micaz sim-sf
	g++ -g -c -o Driver.o Driver.c -I../../../tos/lib/tossim -I$(SFDIR) 
	g++ -o Driver $(DRIVER_OBJS)  Driver.o -lpython2.4 

clean:
	make clean
	rm -f Driver Driver.o *.pyc app.xml
