/* Copyright (c) 2009, Distributed Computing Group (DCG), ETH Zurich.
*  All rights reserved.
*
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*  1. Redistributions of source code must retain the above copyright
*     notice, this list of conditions and the following disclaimer.
*  2. Redistributions in binary form must reproduce the above copyright
*     notice, this list of conditions and the following disclaimer in the
*     documentation and/or other materials provided with the distribution.
*  3. Neither the name of the copyright holders nor the names of
*     contributors may be used to endorse or promote products derived
*     from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS `AS IS'
*  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
*  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
*  ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS
*  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
*  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, LOSS OF USE, DATA,
*  OR PROFITS) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
*  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
*  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
*  THE POSSIBILITY OF SUCH DAMAGE.
*
*  @author Lars Schor <lschor@ee.ethz.ch>
* 
*/

#ifndef HTTP_H
#define HTTP_H

enum {
	HTTP_CONTINUE = 100, 
	HTTP_SWITCHING_PROTOCOLS = 101, 
	HTTP_PROCESSING = 102, 
	HTTP_OK = 200, 
	HTTP_CREATED = 201, 
	HTTP_ACCEPTED = 202, 
	HTTP_NON_AUTHORITATIVE_INFORMATION = 203, 
	HTTP_NO_CONTENT = 204, 
	HTTP_RESET_CONTENT = 205, 
	HTTP_PARTIAL_CONTENT = 206, 
	HTTP_MULTI_STATUS = 207, 
	HTTP_IM_USED = 226, 
	HTTP_MULTIPLE_CHOICES = 300, 
	HTTP_MOVED_PERMANENTLY = 301, 
	HTTP_FOUND = 302, 
	HTTP_SEE_OTHER = 303, 
	HTTP_NOT_MODIFIED = 304, 
	HTTP_USE_PROXY = 305, 
	HTTP_RESERVED = 306, 
	HTTP_TEMPORARY_REDIRECT = 307, 
	HTTP_BAD_REQUEST = 400, 
	HTTP_UNAUTHORIZED = 401, 
	HTTP_PAYMENT_REQUIRED = 402, 
	HTTP_FORBIDDEN = 403, 
	HTTP_NOT_FOUND = 404, 
	HTTP_METHOD_NOT_ALLOWED = 405, 
	HTTP_NOT_ACCEPTABLE = 406, 
	HTTP_PROXY_AUTHENTICATION_REQUIRED = 407, 
	HTTP_REQUEST_TIMEOUT = 408, 
	HTTP_CONFLICT = 409, 
	HTTP_GONE = 410, 
	HTTP_LENGTH_REQUIRED = 411, 
	HTTP_PRECONDITION_FAILED = 412, 
	HTTP_REQUEST_ENTITY_TOO_LARGE = 413, 
	HTTP_REQUEST_URI_TOO_LONG = 414, 
	HTTP_UNSUPPORTED_MEDIA_TYPE = 415, 
	HTTP_REQUESTED_RANGE_NOT_SATISFIABLE_ = 416, 
	HTTP_EXPECTATION_FAILED = 417, 
	HTTP_UNPROCESSABLE_ENTITY = 422, 
	HTTP_LOCKED = 423, 
	HTTP_FAILED_DEPENDENCY = 424, 
	HTTP_UPGRADE_REQUIRED = 426, 
	HTTP_INTERNAL_SERVER_ERROR = 500, 
	HTTP_NOT_IMPLEMENTED = 501, 
	HTTP_BAD_GATEWAY = 502, 
	HTTP_SERVICE_UNAVAILABLE = 503, 
	HTTP_GATEWAY_TIMEOUT_ = 504, 
	HTTP_HTTP_VERSION_NOT_SUPPORTED = 505, 
	HTTP_VARIANT_ALSO_NEGOTIATES = 506, 
	HTTP_INSUFFICIENT_STORAGE = 507, 
	HTTP_NOT_EXTENDED = 510, 
}; 

enum {
	HTTP_GET = 0, 
	HTTP_POST = 1,
	HTTP_PUT = 2, 
	HTTP_DELETE = 3,
}; 

enum {
	HTTP_1_0 = 0,  
	HTTP_1_1 = 1, 
}; 

enum {
	HTTP_LEN_START = 33,
}; 


#define END_LINE "\r\n"

#endif /* HTTP_H */
