COMPONENT=NwkC

CFLAGS += -I$(TOSDIR)/lib/mac/tkn154 \
	  -I$(TOSDIR)/lib/mac/tkn154/dummies \
	  -I$(TOSDIR)/lib/mac/tkn154/interfaces/MCPS \
	  -I$(TOSDIR)/lib/mac/tkn154/interfaces/MLME \
	  -I$(TOSDIR)/lib/mac/tkn154/interfaces/private \
	  -I$(TOSDIR)/lib/mac/tkn154/interfaces/public \
	  -I$ ./ \
	  -I$ ./interfaces \
	  -I$ ./interfaces/private \
	  -I$(TOSDIR)/platforms/micaz/mac/tkn154 \
	  -I$(TOSDIR)/platforms/telosb/mac/tkn154 \
	  -I$(TOSDIR)/platforms/telosb/mac/tkn154/timer \
	  -I$(TOSDIR)/chips/cc2420_tkn154

include $(MAKERULES)
