# the default timestamping precision is TMilli
# to set timestamping precision to 32kHz, uncomment the following line
# PFLAGS+=-DDFRF_32KHZ 
# to set timestamping precision to 1 microsecond, uncomment the following line
# PFLAGS+=-DDFRF_MICRO

COMPONENT=BaseStationC
CFLAGS += -DCC2420_NO_ACKNOWLEDGEMENTS
CFLAGS += -DCC2420_NO_ADDRESS_RECOGNITION

include $(VUMAKERULES)

