create table CEAM (
   ID SMALLINT NOT NULL ,
   Temperatura DOUBLE NOT NULL ,
   Temperatura_B DOUBLE NOT NULL ,
   Humedad DOUBLE NOT NULL ,
   Humedad_B DOUBLE NOT NULL ,
   Medidas SMALLINT NOT NULL,
   Fecha DATETIME NOT NULL,
   SEC SMALLINT NOT NULL,
   PRIMARY KEY (ID, Fecha)
)TYPE=InnoDB ;

create table motas (ID SMALLINT NOT NULL, ID_Padre SMALLINT NOT NULL, Fecha DATETIME NOT NULL)TYPE=InnoDB;
create table topologia (ID SMALLINT NOT NULL, ID_Padre SMALLINT NOT NULL, Voltaje DOUBLE NOT NULL , ETX DOUBLE NOT NULL, Fecha DATETIME NOT NULL, SEC SMALLINT NOT NULL, Recuperado SMALLINT NOT NULL, PRIMARY KEY (ID, Fecha))TYPE=InnoDB;
