echo off
SET C51INC=C:\Keil\C51\INC\Nordic\;C:\Keil\C51\INC\
SET C51LIB=C:\Keil\C51\LIB
SET CPU_TYPE=nRF24E1
SET CPU_VENDOR=Nordic
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
echo on
rem RUNNING ASSEMBLER
C:\Keil\C51\BIN\A51.EXE "STARTUP.A51" SET (SMALL) DEBUG EP
C:\Keil\C51\BIN\C51.EXE "app.c" LARGE SYMBOLS BROWSE DEBUG OBJECTEXTEND PRINT(.\app.lst) OBJECT(.\app.obj)
C:\Keil\C51\BIN\BL51.EXE "startup.obj", "app.obj" TO "app" PRINT (app.map) RAMSIZE(256) REGFILE(app.reg)
C:\Keil\C51\BIN\OH51.EXE "app" 
