# $Id$

#
# Copyright (c) 2010 Data & Knowledge Engineering Research Center,
#                    Harbin Institute of Technology, P. R. China.
# All rights reserved.
#

##
# @author: LIU Yu <pineapple.liu@gmail.com>
# @date:   Jun 22, 2010
#

COMPONENT = SenseAppC

HITDKEDIR ?= /opt/tinyos-2.x-contrib/hitdke
TOSMAKE_PATH += $(HITDKEDIR)/support/make
DATASOURCE = $(HITDKEDIR)/tos/lib/tossim/synsb/data/IntelLab/tossim-db.xml

include $(MAKERULES)

