# $Id$

#
# Copyright (c) 2010 Data & Knowledge Engineering Research Center,
#                    Harbin Institute of Technology, P. R. China.
# All rights reserved.
#

## 
# @author: LIU Yu <pineapple.liu@gmail.com>
# @date:   Jun 18 2010
#

COMPONENT = SenseAppC

HITDKEDIR ?= ../..
SENSORBOARD ?= synsb

ifeq ($(SENSORBOARD),synsb)

  include $(HITDKEDIR)/support/make/synsb.rules

else

  include $(MAKERULES)

endif
