#period of timesync msg broadcast and the period of reference broadcast
PFLAGS += -DTIMESYNC_POLLER_RATE=20
PFLAGS += -DTS_MICRO

ifndef COMPONENT
    COMPONENT=TestTimeStampingC
endif

include ../Makerules

