COMPONENT=DictionaryDemoC

# Choose a flash type:
#CFLAGS += -I../../media/AT45DB
CFLAGS += -I../../media/STM25P

# Default include directories:
CFLAGS += -I../../ -I../../core 
CFLAGS += -I../../interfaces 
CFLAGS += -I../../boot
CFLAGS += -I../../../../tos/lib/State 

include $(MAKERULES)


