COMPONENT=DictionaryDemoC

# Make sure you include paths to Blackbook!
# /tos/lib/blackbook
# /tos/lib/blackbook/boot
# /tos/lib/blackbook/core
# /tos/lib/blackbook/interfaces

# .. And your platform dependant DirectStorage add-ons to access flash
# /tos/chips/stm25p  - telos
# /tos/chips/at45db  - mica*


include $(MAKERULES)


