/*
 * NewJPanel.java
 *
 * Created on August 7, 2008, 12:23 AM
 */

package simx.react.guibase;

/**
 *
 * @author  pstickne
 */
public class MainToolbar extends javax.swing.JToolBar {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form NewJPanel */
    public MainToolbar() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        btnTimeControl = new javax.swing.JButton();
        btnConsole = new javax.swing.JButton();
        btnWatch = new javax.swing.JButton();
        btnTopo = new javax.swing.JButton();
        btnTemplate = new javax.swing.JButton();

        btnTimeControl.setText("Time");
        btnTimeControl.setFocusable(false);
        btnTimeControl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTimeControl.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTimeControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeControlActionPerformed(evt);
            }
        });

        btnConsole.setText("Console");
        btnConsole.setFocusable(false);
        btnConsole.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsole.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsoleActionPerformed(evt);
            }
        });

        btnWatch.setText("Watch");
        btnWatch.setFocusable(false);
        btnWatch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWatch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWatchActionPerformed(evt);
            }
        });

        btnTopo.setText("Topology");
        btnTopo.setFocusable(false);
        btnTopo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTopo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTopo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopoActionPerformed(evt);
            }
        });

        btnTemplate.setText("Template");
        btnTemplate.setFocusable(false);
        btnTemplate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTemplate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemplateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnTimeControl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTopo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnWatch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTemplate))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnTimeControl)
                .addComponent(btnConsole)
                .addComponent(btnTopo)
                .addComponent(btnWatch)
                .addComponent(btnTemplate))
        );
    }//GEN-END:initComponents

    private void btnTimeControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeControlActionPerformed
        // TODO add your handling code here:
        return;
    }//GEN-LAST:event_btnTimeControlActionPerformed

    private void btnConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsoleActionPerformed
        // TODO add your handling code here:
        return;
    }//GEN-LAST:event_btnConsoleActionPerformed

    private void btnWatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWatchActionPerformed
        // TODO add your handling code here:
        return;
    }//GEN-LAST:event_btnWatchActionPerformed

    private void btnTopoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopoActionPerformed
        // TODO add your handling code here:
        return;
    }//GEN-LAST:event_btnTopoActionPerformed

    private void btnTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemplateActionPerformed
        // TODO add your handling code here:
        return;
    }//GEN-LAST:event_btnTemplateActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConsole;
    public javax.swing.JButton btnTemplate;
    public javax.swing.JButton btnTimeControl;
    public javax.swing.JButton btnTopo;
    public javax.swing.JButton btnWatch;
    // End of variables declaration//GEN-END:variables
    
}
