#ifndef SOLARSRC_H_INCLUDED
#define SOLARSRC_H_INCLUDED

#define _NUMEPOCHS 12L
#define _HRS_PER_DAY 24L
#define _DAYLENGTH (_HRS_PER_DAY * 60L)

#define _EPOCHLENGTH (_DAYLENGTH / _NUMEPOCHS)

#define _HRS_PER_EP (_HRS_PER_DAY / _NUMEPOCHS)

#define _DAYNIGHT_THOLD  (_HRS_PER_EP * 1000000L)
#endif
