#period of timesync msg broadcast and the period of reference broadcast
PFLAGS += -DTIMESYNC_POLLER_RATE=250

ifndef COMPONENT
    COMPONENT=TestTimeSyncMessageC
endif

include ../../Makerules

