package com.rincon.tunit.report;

/*
 * Copyright (c) 2005-2006 Rincon Research Corporation
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the
 *   distribution.
 * - Neither the name of the Rincon Research Corporation nor the names of
 *   its contributors may be used to endorse or promote products derived
 *   from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
 * RINCON RESEARCH OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE
 */

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

import org.apache.log4j.Logger;


/**
 * Write information about an individual suite of tests to XML so it can
 * be parsed and turned into HTML by ant's junitreport task.
 * 
 * We don't do anything fancy with writing the XML here, because it would
 * be kind of overkill.
 * 
 * The only DTD I could find on how Ant parses out XML and turns it into
 * HTML is from the XMLConstants.java file in 
 * package org.apache.tools.ant.taskdefs.optional.junit.  This comment is
 * graciously copy-pasted below.
 *
 * <p> Interface groups XML constants.
 * Interface that groups all constants used throughout the <tt>XML</tt>
 * documents that are generated by the <tt>XMLJUnitResultFormatter</tt>.
 * <p>
 * As of now the DTD is:
 * <code><pre>
 * &lt;!ELEMENT testsuites (testsuite*)&gt;
 *
 * &lt;!ELEMENT testsuite (properties, testcase*,
 *                    failure?, error?,
 *                     system-out?, system-err?)&gt;
 * &lt;!ATTLIST testsuite name      CDATA #REQUIRED&gt;
 * &lt;!ATTLIST testsuite tests     CDATA #REQUIRED&gt;
 * &lt;!ATTLIST testsuite failures  CDATA #REQUIRED&gt;
 * &lt;!ATTLIST testsuite errors    CDATA #REQUIRED&gt;
 * &lt;!ATTLIST testsuite time      CDATA #REQUIRED&gt;
 * &lt;!ATTLIST testsuite package   CDATA #IMPLIED&gt;
 * &lt;!ATTLIST testsuite id        CDATA #IMPLIED&gt;
 *
 *
 * &lt;!ELEMENT properties (property*)&gt;
 *
 * &lt;!ELEMENT property EMPTY&gt;
 *   &lt;!ATTLIST property name  CDATA #REQUIRED&gt;
 *   &lt;!ATTLIST property value CDATA #REQUIRED&gt;
 *
 * &lt;!ELEMENT testcase (failure?, error?)&gt;
 *   &lt;!ATTLIST testcase name       CDATA #REQUIRED&gt;
 *   &lt;!ATTLIST testcase classname  CDATA #IMPLIED&gt;
 *   &lt;!ATTLIST testcase time       CDATA #REQUIRED&gt;
 *
 * &lt;!ELEMENT failure (#PCDATA)&gt;
 *  &lt;!ATTLIST failure message CDATA #IMPLIED&gt;
 *  &lt;!ATTLIST failure type    CDATA #REQUIRED&gt;
 *
 * &lt;!ELEMENT error (#PCDATA)&gt;
 *   &lt;!ATTLIST error message CDATA #IMPLIED&gt;
 *   &lt;!ATTLIST error type    CDATA #REQUIRED&gt;
 *
 * &lt;!ELEMENT system-err (#PCDATA)&gt;
 *
 * &lt;!ELEMENT system-out (#PCDATA)&gt;
 *
 * @author David Moss
 *
 */
public class WriteXmlReport {

  /** The current report we're writing */
  private TestReport report;
  
  /** The file we'll write the XML test report to */
  private File outFile;
  
  /** Logging */
  private static Logger log = Logger.getLogger(WriteXmlReport.class);
  
  /**
   * Constructor
   * @param myReport
   * @param outDirectory
   */
  public WriteXmlReport(TestReport myReport, File outDirectory) {
    log = Logger.getLogger(getClass());
    report = myReport;
    if(!outDirectory.exists()) {
      log.debug("Creating directory " + outDirectory.getAbsolutePath());
      outDirectory.mkdirs();
    }
    
    File myFile = new File(outDirectory.getAbsolutePath() 
        + "/TEST-" 
        + report.getPackage()
        + ".xml");
    
    log.debug("Writing report " + myFile.getAbsolutePath());
    
    if(myFile.exists()) {
      log.debug("Deleting previous " + myFile.getAbsoluteFile());
      myFile.delete();
    }
    
    outFile = myFile;
  }
  
  /**
   * Write the XML file.
   * @throws IOException if the file can't be created for writing
   */
  public void write() throws IOException {
    PrintWriter out = new PrintWriter(
        new BufferedWriter(new FileWriter(outFile)));
    log.debug("Logging results to " + outFile.getAbsoluteFile());
    out.write(beginHeader());
    out.write(getTests());
    out.write(getSystemOut());
    out.write(getSystemErr());
    out.write(endHeader());
    out.close();
  }
  
  /**
   * Start the XML report header
   * @return
   */
  private String beginHeader() {
    //<testsuite name="<package>" tests="1" failures="1" errors="0" time="0.789">
    String header = "<testsuite name=\"";
    header += report.getPackage() + "\" tests=\"";
    header += report.getTotalTests() + "\" failures=\"";
    header += report.getTotalFailures() + "\" errors=\"";
    header += report.getTotalErrors() + "\" time=\"";
    header += report.getTotalDuration() + "\">\n";
    return header;
  }
  
  /**
   * Create the XML data for all the test results
   * @return
   */
  private String getTests() {
    String xml = "";
    for(int i = 0; i < report.getTotalTests(); i++) {
      xml += toXml(report.getTestResult(i));
    }
    
    return xml;
  }
  
  /**
   * Get any system output to add to the xml information.
   * @return
   */
  private String getSystemOut() {
    String output = report.getSystemOut();
    String returnLine = "";
    if(!output.matches("")) {
      returnLine += "<system-out>\n";
      returnLine += makeXmlFriendly(output);
      returnLine += "</system-out>\n";
    }
    
    return returnLine;
  }
  

  /**
   * Get any system errors to add to the xml information
   * @return
   */
  private String getSystemErr() {
    String errors = report.getSystemErr();
    String returnLine = "";
    if(!errors.matches("")) {
      returnLine += "<system-err>\n";
      returnLine += makeXmlFriendly(errors);
      returnLine += "</system-err>\n";
    }
    
    return returnLine;
  }
  
  /**
   * Close off the XML report header
   * @return
   */
  private String endHeader() {
    return "</testsuite>";
  }
  
  private String toXml(TestResult result) {
    String xml = "";
    xml += "  <testcase classname=\"";
    xml += report.getPackage() + "\" "; // doesn't matter
    xml += "name=\"" + makeXmlFriendly(result.getTestName()) + "\n" + result.getSourceCodeLineNumber() + "\" ";
    xml += "time=\"" + result.getDuration() + "\"";
    
    if(!result.isError() && !result.isFailure()) {
      // Success.
      xml += "/>";
      xml += "\n\n";
      return xml;
    }
    
    // Failure or error.. go into detail.
    xml += ">\n";
    xml += "    <";
    if(result.isError()) {
      xml += "error";
    } else {
      xml += "failure";
    }
    
    xml += " type=\"" + makeXmlFriendly(result.getProblemType()) + "\">";  // doesn't matter
    xml += makeXmlFriendly(result.getFailMsg()) + "</";
    
    if(result.isError()) {
      xml += "error";
    } else {
      xml += "failure";
    }
    
    xml += ">\n";
    xml += "  </testcase>";
    xml += "\n\n";
    return xml;
    
  }
  
  /**
   * XML hates things like quotes and < >'s embedded in tags.
   * @param xml
   * @return
   */
  private String makeXmlFriendly(String xml) {
    xml = xml.replaceAll("\"","&quot;");
    xml = xml.replaceAll("<", "&lt;");
    xml = xml.replaceAll(">", "&gt;");
    return xml;
  }
}
