# $Id$ #

# author: Mustafa Yuecel <mustafa.yuecel@alumni.ethz.ch> #

ifndef COMPONENT
#COMPONENT = TestLedAppC
#COMPONENT = TestButtonAppC
COMPONENT = TestUartStreamAppC
endif
TOSMAKE_PATH += ../../support/make
include $(MAKERULES)
#OPTFLAGS = -Os
