# $Id$ #

# author: Mustafa Yuecel <mustafa.yuecel@alumni.ethz.ch> #

ifndef COMPONENT
#COMPONENT=TestLedAppC
COMPONENT=TestButtonAppC
endif
#OPTFLAGS = -O2
TOSMAKE_PATH += ../../support/make
include $(MAKERULES)
