/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'ReactReplyMsg'
 * message type.
 */

package simx.mig;

public class ReactReplyMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 2;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 204;

    /** Create a new ReactReplyMsg of size 2. */
    public ReactReplyMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new ReactReplyMsg of the given data_length. */
    public ReactReplyMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReactReplyMsg with the given data_length
     * and base offset.
     */
    public ReactReplyMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReactReplyMsg using the given byte array
     * as backing store.
     */
    public ReactReplyMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReactReplyMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public ReactReplyMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReactReplyMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public ReactReplyMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReactReplyMsg embedded in the given message
     * at the given base offset.
     */
    public ReactReplyMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReactReplyMsg embedded in the given message
     * at the given base offset and length.
     */
    public ReactReplyMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <ReactReplyMsg> \n";
      try {
        s += "  [status=0x"+Long.toHexString(get_status())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [ve_start_byte=0x"+Long.toHexString(get_ve_start_byte())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: status
    //   Field type: short, signed
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'status' is signed (true).
     */
    public static boolean isSigned_status() {
        return true;
    }

    /**
     * Return whether the field 'status' is an array (false).
     */
    public static boolean isArray_status() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'status'
     */
    public static int offset_status() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'status'
     */
    public static int offsetBits_status() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'status'
     */
    public short get_status() {
        return (short)getUIntBEElement(offsetBits_status(), 8);
    }

    /**
     * Set the value of the field 'status'
     */
    public void set_status(short value) {
        setUIntBEElement(offsetBits_status(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'status'
     */
    public static int size_status() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'status'
     */
    public static int sizeBits_status() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: ve_start_byte
    //   Field type: byte, signed
    //   Offset (bits): 8
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 've_start_byte' is signed (true).
     */
    public static boolean isSigned_ve_start_byte() {
        return true;
    }

    /**
     * Return whether the field 've_start_byte' is an array (false).
     */
    public static boolean isArray_ve_start_byte() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 've_start_byte'
     */
    public static int offset_ve_start_byte() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 've_start_byte'
     */
    public static int offsetBits_ve_start_byte() {
        return 8;
    }

    /**
     * Return the value (as a byte) of the field 've_start_byte'
     */
    public byte get_ve_start_byte() {
        return (byte)getSIntBEElement(offsetBits_ve_start_byte(), 8);
    }

    /**
     * Set the value of the field 've_start_byte'
     */
    public void set_ve_start_byte(byte value) {
        setSIntBEElement(offsetBits_ve_start_byte(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 've_start_byte'
     */
    public static int size_ve_start_byte() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 've_start_byte'
     */
    public static int sizeBits_ve_start_byte() {
        return 8;
    }

}
