COMPONENT=RadioCountToLedsC

CFLAGS+=-DCC2500_DEFAULT_CHANNEL=20
CFLAGS+=-DCC1100_DEFAULT_CHANNEL=20

CFLAGS+=-I../../tos/chips/ccxx00
CFLAGS+=-I../../tos/chips/ccxx00/acks
CFLAGS+=-I../../tos/chips/ccxx00/alarm
CFLAGS+=-I../../tos/chips/ccxx00/am
CFLAGS+=-I../../tos/chips/ccxx00/cc1100
CFLAGS+=-I../../tos/chips/ccxx00/cc2500
CFLAGS+=-I../../tos/chips/ccxx00/csma
CFLAGS+=-I../../tos/chips/ccxx00/init
CFLAGS+=-I../../tos/chips/ccxx00/interfaces
CFLAGS+=-I../../tos/chips/ccxx00/link
CFLAGS+=-I../../tos/chips/ccxx00/lpl/alwayson
CFLAGS+=-I../../tos/chips/ccxx00/packet
CFLAGS+=-I../../tos/chips/ccxx00/powermanager
CFLAGS+=-I../../tos/chips/ccxx00/receive
CFLAGS+=-I../../tos/chips/ccxx00/select
CFLAGS+=-I../../tos/chips/ccxx00/splitcontrolmanager
CFLAGS+=-I../../tos/chips/ccxx00/spi
CFLAGS+=-I../../tos/chips/ccxx00/transmit
CFLAGS+=-I../../tos/chips/ccxx00/unique

include $(MAKERULES)

