# This is designed to be included from a TOS application Makefile.
#
# Author: Paul Stickney, May 2008

SIMX ?=simx
SIMXLIB ?=$(SIMX)/lib/simx
SIMX_LEDS_DIR ?=$(SIMXLIB)/leds

CFLAGS+= -I$(SIMX_LEDS_DIR)
