COMPONENT=src/TestNeighborTableC
CFLAGS += -Isrc

#CFLAGS += -I$(TOSDIR)/lib/printf
CFLAGS += -I$(TOSCONTRIB)/csau/misc/tos/types
CFLAGS += -I$(TOSCONTRIB)/csau/misc/tos/lib/neighbortable
CFLAGS += -I$(TOSCONTRIB)/csau/misc/tos/lib/neighbortable/example

CLEAN_EXTRA = simbuild build app.xml

include $(MAKERULES)