#!/usr/bin/env python
# -*- python -*-

import sys, time, getopt, socket

class RebootMote:
    def __init__(self, when, port):
        self.when = when
        self.port = port

    def get_command(self,imgn):
        remaining = self.when - time.time()
        remainingms = int(remaining * 1000)
        return "nwprog boot %i %i\n" % (imgn, remainingms)

    def reboot(self,ipaddr,imgn):
        rv = True
        ipaddr = ipaddr.strip().lower()
        s = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM)
        cmd = self.get_command(imgn)
        # print cmd
        s.sendto(cmd, (ipaddr, self.port))
        s.settimeout(2)
        try:
            data, addr = s.recvfrom(1024)
            if addr[0] != ipaddr:
                rv = False
            else:
                print data.strip()
        except:
            rv = False
        s.close()
        return rv
        

def print_usage():
    print
    print "  %s [options] [ip-list]" % sys.argv[0]
    print "    -i  --imageno   the image number to boot"
    print "    -w  --when      how long from now to reboot (seconds)"
    print "    -m  --motelist  a file containing a list of mote ipv6 addresses"
    print "    -p  --port      the port the shell is running on (default: 2000)"
    print

if __name__ == '__main__':
    try:
        opts, args = getopt.getopt(sys.argv[1:], "i:w:m:p:",
                                   ["--imageno", "--when", "--moteliist", "--port"])
    except getopt.GetoptError, err:
        print str(err)
        print_usage()
        sys.exit(1)

    imageNo = None
    when = None
    moteList = None
    shellPort = 2000

    for o, a in opts:
        if o in ['-i', '--imageno']:
            imageNo = int(a)
        elif o in ['-w', '--when']:
            when = int(a)
        elif o in ['-m', '--motelist']:
            moteList = a
        elif o in ['-p', '--port']:
            shellPort = int(a)

    if imageNo == None or when == None:
        print_usage()
        sys.exit(1)

    reprogList = [(i, False) for i in args]
    if moteList != None:
        print "Reading addresses from", moteList
        fp = open (moteList, "r")
        reprogList += [(l.strip(), False) for l in fp.readlines()]
        fp.close()

    motes_remaining = True
    r = RebootMote(time.time() + when, shellPort)

    # print "Scheduling network reboot for %s" % time.localtime(r.when)

    while time.time() < r.when and motes_remaining == True:
        motes_remaining = False
        for i in range(0,len(reprogList)):
            ip, success = reprogList[i]
            if success == True: continue
            print "Rebooting %s" % ip
            if r.reboot(ip, imageNo):
                reprogList[i] = (ip, True)
            else:
                motes_remaining = True

    if motes_remaining == False:
        print "All motes scheduled for reboot!"
