COMPONENT=BlackbookBridgeC

CFLAGS += -I./BBootBridge
CFLAGS += -I./BCleanBridge
CFLAGS += -I./BDictionaryBridge
CFLAGS += -I./BFileDeleteBridge
CFLAGS += -I./BFileDirBridge
CFLAGS += -I./BFileReadBridge
CFLAGS += -I./BFileWriteBridge

# Compiler optimizer flag:
CFLAGS += -Os

include $(MAKERULES)

