# Path to WMTP
PFLAGS += -I../../tos/lib/net/wmtp
PFLAGS += -I../../tos/lib/net/wmtp/interfaces
PFLAGS += -I../../tos/lib/net/wmtp/modules
PFLAGS += -I../../tos/lib/net/wmtp/adapter

COMPONENT=BaseStationC
CFLAGS += -DCC2420_NO_ACKNOWLEDGEMENTS
CFLAGS += -DCC2420_NO_ADDRESS_RECOGNITION

include $(MAKERULES)

