COMPONENT=TestC

CFLAGS+=-I${TOSROOT}/tos/chips/ccxx00_multiple/
CFLAGS+=-I${TOSROOT}/tos/chips/ccxx00_multiple/init
CFLAGS+=-I${TOSROOT}/tos/chips/ccxx00_multiple/interfaces
CFLAGS+=-I${TOSROOT}/tos/chips/ccxx00_multiple/select
CFLAGS+=-I${TOSROOT}/tos/chips/ccxx00_multiple/spi

include $(MAKERULES)

