 Article 2904 of comp.binaries.ibm.pc.d:
 From: c31293@tansei.cc.u-tokyo.JUNET (Kenji Rikitake)
 Newsgroups: comp.binaries.ibm.pc.d
 Subject: lzhuf.c copyright condition
 Message-ID: <3279@tansei.cc.u-tokyo.JUNET>
 Date: 9 Apr 89 15:22:55 GMT
 Reply-To: c31293@tansei.cc.u-tokyo.JUNET (Kenji Rikitake)
 Organization: ICEE Software Development Group,
                  Management Development Institute, Tokyo, Japan

I posted Lzhuf.c at c.b.i.p. Since Japanese Copyright Law does not require
expressing the owner of copyright by "(C)....", I did not put copyright
message on it.

LZHUF.C is copyrighted. The authors, Yoshizaki, Okumura, and myself,
do not allow it being used in ANY commercial softwares.

I would appreciate if you put the following lines at the lzhuf.c source:

 /*
 LZHUF.C (c)1989 by Haruyasu Yoshizaki, Haruhiko Okumura, and Kenji Rikitake.
 All rights reserved. Permission granted for non-commercial use.
 */

 -- Kenji
 -- 
 Kenji Rikitake: rikitake@wadalab.t.u-tokyo.junet +81 3 812 2111 ext 7411
 Kenji%dctwcs.das.net@(Sun.COM|uunet.uu.net) +81 3 351 5977
 Michihiro Matsumoto Office / MDI: +81 3 823 7943
