COMPONENT = sunlogC
PFLAGS +=-I%T/lib/TinyRely
PFLAGS +=-I%T/lib/Flash
PFLAGS +=-I%T/lib/Flash/AT45DB
PFLAGS +=-I/nfs/raptor/scratch1/tinyos-1.1.0/tinyos-1.x/apps/fluxServer/runtime
include /nfs/raptor/scratch1/tinyos-1.1.0/tinyos-1.x/apps/Makerules

