/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file implements the functions for encoding and decoding the
 * 'img_stat' message type. See img_stat.h for more details.
 */

#include <message.h>
#include "img_stat.h"

uint16_t img_stat_node_id_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 0, 16);
}

void img_stat_node_id_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 0, 16, value);
}

uint8_t img_stat_type_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 16, 8);
}

void img_stat_type_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 16, 8, value);
}

uint16_t img_stat_width_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 24, 16);
}

void img_stat_width_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 24, 16, value);
}

uint16_t img_stat_height_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 40, 16);
}

void img_stat_height_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 40, 16, value);
}

uint32_t img_stat_data_size_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 56, 32);
}

void img_stat_data_size_set(tmsg_t *msg, uint32_t value)
{
  tmsg_write_ube(msg, 56, 32, value);
}

uint32_t img_stat_timeAcq_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 88, 32);
}

void img_stat_timeAcq_set(tmsg_t *msg, uint32_t value)
{
  tmsg_write_ube(msg, 88, 32, value);
}

uint32_t img_stat_timeProc_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 120, 32);
}

void img_stat_timeProc_set(tmsg_t *msg, uint32_t value)
{
  tmsg_write_ube(msg, 120, 32, value);
}

