#if LGL_CONTRIB is not defined, see stanford-lgl/README file
COMPONENT=cameraJpegTestC

PFLAGS += -I$(LGL_CONTRIB)/support/sdk/c/compress
PFLAGS += -I$(LGL_CONTRIB)/libs/BigMsg
CFLAGS += -DPXA27X_FREQ=208
#CFLAGS += -Wcast-align -Wpadded -Wpacked
include ../Makerules