#if LGLDIR is not defined, see stanford-lgl/README file
COMPONENT=cameraJpegTestC

PFLAGS += -I$(LGLDIR)/support/sdk/c/compress
PFLAGS += -I$(LGLDIR)/libs/BigMsg
CFLAGS += -DPXA27X_FREQ=208
#CFLAGS += -Wcast-align -Wpadded -Wpacked
include ../Makerules