 #
 # This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 # This class includes values of some nesC constants from
 # /home/stevedh/src/svn/code/b6lowpan/trunk/tos/lib/net/blip/shell/BinaryShell.h.
 #/

class ShellConstants:
    BSHELL_UPTIME = 6
    BSHELL_ECHO = 2
    BSHELL_PING6 = 3
    BSHELL_NWPROG = 8
    BSHELL_PING6_REPLY = 4
    BSHELL_PING6_DONE = 5
    BSHELL_ERROR_NOTFOUND = 0
    BSHELL_ERROR = 0
    BSHELL_ENUMERATE = 1
    BSHELL_IDENT = 7

