#!/usr/bin/env mzscheme -u

#lang scheme

(require scheme/port srfi/13 srfi/26
         (file "sensor-net.scm"))

; ssgw 
; 

(define *prot-version* "U ")

(define *listen-port* 7828)

(define *serial-port* "sf@localhost")

(define (set-port! p) (set! *listen-port* p))

(define (set-serial! s) (set! *serial-port* s))

(define (reset-state!) #f)

(define (open-comm-ports s)
  (cond [(string-prefix? "serial@" s) (raise-user-error "serial port connections are not yet supported")
                                      (let* ([serial (string-drop s (string-length "serial@"))]
                                             [sep (string-index serial #\:)]
                                             [speed (if sep (string-drop serial (+ 1 sep)) 57600)] 
                                             [port (if sep (string-take serial sep) serial)])
                                        (open-input-output-file port #:exists 'append))]
        [(string-prefix? "sf@" s) (let* ([sf (string-drop s (string-length "sf@"))]
                                         [sep (string-index sf #\:)]
                                         [port (if sep (string->number (string-drop sf (+ 1 sep))) 9002)] 
                                         [addr (if sep (string-take sf sep) sf)])
                                    (tcp-connect addr port))]
        [else (raise-user-error "no valid serial communication port specified")])
  )

(define (send-to-net line path sout)
  (let* ([msg (read (open-input-bytes line))]
         [encoded (net-encode-mapfile (case (car msg)
                                        [(disseminate) (second msg)]
                                        [(deliver handoff) (third msg)]
                                        [else (raise-user-error "unknown protocol specified: " (car msg))]) path)])
    (printf "received message: ~s~n" msg)
    (printf "~s~n" encoded)))

(define (decode-pkts pkts base) 
  (if (null? pkts) #f
      (if (= (bitwise-and (caar pkts) #x80) 0) (decode-pkts (cdr pkts) base)
          (let loop ([pkts pkts]
                     [seqno (caar pkts)]
                     [msg (cdar pkts)])
            (cond [(null? pkts) (if (= (bitwise-and seqno #x40) 0) (begin (printf "incomplete message~n") #f) 
                                    (net-decode-mapfile msg (build-path base "ssgw")))]
                  [(= (bitwise-and (+ seqno 1) #x3f) (bitwise-and (caar pkts) #x3f)) (loop (cdr pkts) (caar pkts) (append msg (cdar pkts)))]
                  [else (loop (cdr pkts) seqno msg)])))))

(define (main argv)
  (let*-values 
      ([(base) (command-line #:argv argv
                             #:help-labels 
                             "deamon process that keeps connection with sensor network through gateway"
                             "params:" "-base: the name of the base config location as generated by ssbuild"
                             "opens socket for command connections, and forwards received messages to connected clients"
                             "each command or received message is an s-expr, of the following shapes"
                             "commands:"
                             " - (disseminate `msg`) : to disseminate into the whole network"
                             " - (deliver `addr` `msg`) : delliver to a specific node across multiple hops"
                             " - (handoff `addr` `msg`) : handoff a message in direct reach of the GW"
                             "results:"
                             " - {intercept `src` `msg`} : a node sending an intercept message to the gw as its parent"
                             " - {forward `src` `msg`}"
                             " - {send `src` `dst` `msg`}"
                             "ssgw handles the translation between string-literal stymbols and their "
                             "  numeric equivalent on the network"
                             "upon new connection, starts by sending the base config location"
                             #:once-each
                             (("-c" "--comm") serial "name of the serial port to connect to network" (set-serial! serial))
                             (("-p" "--port") port "TCP port to listen on (default 7828)" (set-port! port))
                             (("-r" "--reset") "resets the locally kept state of the network. does not influence the nodes themselves"
                                               (reset-state!))
                             #:args (base) (path->complete-path base))]
       [(sin sout) (open-comm-ports *serial-port*)]
       [(acc-evt) (tcp-accept-evt (tcp-listen *listen-port*))]
       
       [(client-sock-ls) null]       
       [(pkt-hash) (make-hash)])
    
    (printf "SensorScheme gateway deamon~nBase configuration path: ~a~n" base)
    (with-input-from-file (build-path base "ssgw" "config.ncf") read)
    
    (file-stream-buffer-mode sin 'none)
    (file-stream-buffer-mode sout 'none)
    (write-string *prot-version* sout)
    (flush-output sout)
    (when (not (equal? (read-string (string-length *prot-version*) sin) *prot-version*)) (raise-user-error "Network uses incorrect protocol version"))
    
    
    (let loop () 
      (apply sync (handle-evt acc-evt (lambda (s) 
                                        (set! client-sock-ls (cons s client-sock-ls))
                                        (file-stream-buffer-mode (second s) 'line)
                                        (fprintf (second s) "~a~n" base)))
             (handle-evt (read-bytes-evt 1 sin) 
                         (lambda (e) (if (eof-object? e)
                                         (exit 0)
                                         (let* ([bstr (read-bytes (bytes-ref e 0) sin)]
                                                [msgls (bytes->list bstr)]) 
                                           (case (bytes-ref bstr 7)
                                             [(#x71) (case (list-ref msgls 15) 
                                                       [(9 10) (let ([src (integer-bytes->integer bstr #f #t 12 14)])
                                                              (hash-update! pkt-hash src 
                                                                            (lambda (v) (cons (list-tail msgls 16) v)) (lambda () null))
                                                              (unless (= (bitwise-and (bytes-ref bstr 16) #x40) 0)
                                                                (printf "~s : ~a~n" src (decode-pkts (reverse (hash-ref pkt-hash src)) base))
                                                                (hash-remove! pkt-hash src)))]
                                                       [else (printf "unknown collection protocol~n")])]
                                             [else (printf "unknown message type: ~s~n" (list-ref msgls 7))])))))
             (append (map (lambda (s) (handle-evt (eof-evt (car s)) (lambda (ln) 
                                                                      (printf "eof!!~n")
                                                                      (close-input-port (car s))
                                                                      (close-output-port (cadr s))
                                                                      (set! client-sock-ls 
                                                                            (filter (lambda (el) (not (equal? s el)))
                                                                                    client-sock-ls))))) client-sock-ls)
                     (map (lambda (s) (handle-evt (read-bytes-line-evt (car s) 'linefeed) 
                                                  (lambda (ln) (when (not (eof-object? ln)) (send-to-net ln base sout)))))
                          client-sock-ls))) 
      (loop))))

(main (current-command-line-arguments))