//  A2d12ch.h
//#ifndef A2D12CH_H
//#define A2D12CH_H

#define BUFFERLEN 6
#define JIFFIES 0
//default config data
//
#define CONFIG_VREF  REFVOLT_LEVEL_2_5, SHT_SOURCE_ACLK, SHT_CLOCK_DIV_1, SAMPLE_HOLD_4_CYCLES, SAMPCON_SOURCE_SMCLK, SAMPCON_CLOCK_DIV_1

#define CHANNEL1 INPUT_CHANNEL_A0, REFERENCE_VREFplus_AVss
#define CHANNEL2 INPUT_CHANNEL_A1, REFERENCE_VREFplus_AVss
#define CHANNEL3 INPUT_CHANNEL_A2, REFERENCE_VREFplus_AVss
#define CHANNEL4 INPUT_CHANNEL_A3, REFERENCE_VREFplus_AVss
#define CHANNEL5 INPUT_CHANNEL_A4, REFERENCE_VREFplus_AVss
#define CHANNEL6 INPUT_CHANNEL_A5, REFERENCE_VREFplus_AVss
#define CHANNEL7 INPUT_CHANNEL_A6, REFERENCE_VREFplus_AVss
#define CHANNEL8 INPUT_CHANNEL_A7, REFERENCE_VREFplus_AVss
