/**
 * Interface for the RV-8564-C2 real time clock.
 *
 * @author Henrik Makitaavola
 */
interface RV8564
{
  /**
   * Turns the chip on.
   */
  async command void on();

  /**
   * Turns the chip off.
   */
  async command void off();

  /**
   * Checks if the chip is on.
   *
   * @return true if on.
   */
  async command bool isOn();

  /**
   * Enables/disables the interrupts generated by the CLKOUT.
   */
  // TODO(henrik) This needs to be changed because there are different type of 
  //              interrupts generated by the chip.
  async command void enableInterrupt();
  async command void disableInterrupt();

  /**
   * Reads from a register.
   *
   * @param reg The register to be read.
   * @return The value of the register.
   */
  async command uint8_t readRegister(uint16_t reg);

  /**
   * Writes to a register.
   *
   * @param reg The register that is written to.
   * @param value The value that is written to the register.
   */
  async command void writeRegister(uint16_t reg, uint8_t value);
  
  /**
   * Signal when an interrupt occurs.
   */
  async event void fired();
}
