COMPONENT=GyroMagAppC

#defines
CFLAGS += -DUSE_AVCC_REF # approx 0.5 milliamps saving when using AVCC compared to 2.5V or 1.5V internal ref

#CFLAGS += -DLOW_BATTERY_INDICATION

CFLAGS += -DUSE_8MHZ_CRYSTAL

include $(MAKERULES)
