COMPONENT = TestSendingAppC

include $(UPMA_DIR)/chips/cc2420/Makefile.cc2420
CFLAGS += -I$(UPMA_DIR)/interfaces \
	-I$(UPMA_DIR)/lib/macs/bmac \
	-I$(UPMA_DIR)/lib/alarm \
	-I$(UPMA_DIR)/lib/serial \
	-I$(UPMA_DIR)/types \
	-I$(UPMA_DIR)/system \
	-I$(UPMA_DIR)/platforms/$(PLATFORM)

include $(MAKERULES)
	
