COMPONENT = ACMeterAppC
include $(MAKERULES)
PFLAGS += -DCC2420_DEF_CHANNEL=18

# Uncomment this line for ACme Rev.A
# CFLAGS += -I../../tos/sensorboards/ACme/
# Uncomment this line for ACmeX2 (Rev.B)
CFLAGS += -I../../tos/sensorboards/ACmeX2/
