# the default timestamping precision is TMilli
# to set timestamping precision to 32kHz, uncomment the following line
# PFLAGS+=-DDFRF_32KHZ

COMPONENT=TestBroadcastPolicyAppC

CFLAGS += -I$(VUTOSDIR)/lib/dfrf
CFLAGS += -I$(VUTOSDIR)/lib/remotecontrol
CFLAGS += -I$(VUTOSDIR)/lib/misc

include $(VUMAKERULES)
 