#ifndef _H_hardware_h
#define _H_hardware_h

#include "msp430hardware.h"
//#include "MSP430ADC12.h"
//#include "CC2420Const.h"
//#include "AM.h"

// P1
TOSH_ASSIGN_PIN(TILT_SENSE, 1, 7);
TOSH_ASSIGN_PIN(EXT_INT4, 1, 6);
TOSH_ASSIGN_PIN(EXT_VCC_SENSE, 1, 5);
TOSH_ASSIGN_PIN(CC2500_GDO2, 1, 4);
TOSH_ASSIGN_PIN(CC2500_GDO0, 1, 3);
TOSH_ASSIGN_PIN(CC1101_GDO2, 1, 2);
TOSH_ASSIGN_PIN(BSL_TX, 1, 1);
TOSH_ASSIGN_PIN(CC1101_GDO0, 1, 0);

// P2
TOSH_ASSIGN_PIN(LNAPA_CC1101_MODE, 2, 7);
TOSH_ASSIGN_PIN(EXT_INT3, 2, 6);
TOSH_ASSIGN_PIN(ROSC, 2, 5);
TOSH_ASSIGN_PIN(NBD_CC1101_GDO2, 2, 4);
TOSH_ASSIGN_PIN(NBD_CC1101_GDO0, 2, 3);
TOSH_ASSIGN_PIN(BSL_RX, 2, 2);
TOSH_ASSIGN_PIN(AUX_ENABLE, 2, 1);
TOSH_ASSIGN_PIN(EXT_INT5, 2, 0);

// P3
TOSH_ASSIGN_PIN(UART1_RX, 3, 7);
TOSH_ASSIGN_PIN(UART1_TX, 3, 6);
TOSH_ASSIGN_PIN(NBD_CC1101_CS, 3, 5);
TOSH_ASSIGN_PIN(GPS_CS, 3, 4);
TOSH_ASSIGN_PIN(SPI0_CLK, 3, 3);
TOSH_ASSIGN_PIN(SPI0_MISO, 3, 2);
TOSH_ASSIGN_PIN(SPI0_MOSI, 3, 1);
TOSH_ASSIGN_PIN(CC1101_CS, 3, 0);

// P4
TOSH_ASSIGN_PIN(FLASH_HOLD, 4, 7);
TOSH_ASSIGN_PIN(CTRL_P46, 4, 6);
TOSH_ASSIGN_PIN(PA_ENABLE, 4, 5);
TOSH_ASSIGN_PIN(FLASH_CS, 4, 4);
TOSH_ASSIGN_PIN(LNA_ENABLE, 4, 3);
TOSH_ASSIGN_PIN(ACCEL_ENABLE, 4, 2);
TOSH_ASSIGN_PIN(RS232_ENABLE, 4, 1);
TOSH_ASSIGN_PIN(SDIO_CLK, 4, 0);

// P5
TOSH_ASSIGN_PIN(CC2500_CS, 5, 7);
TOSH_ASSIGN_PIN(CTRL_P56, 5, 6);
TOSH_ASSIGN_PIN(CTRL_P55, 5, 5);
TOSH_ASSIGN_PIN(LNAPA_CC2500_MODE, 5, 4);
TOSH_ASSIGN_PIN(SPI1_CLK, 5, 3);
TOSH_ASSIGN_PIN(SPI1_MISO, 5, 2);
TOSH_ASSIGN_PIN(SPI1_MOSI, 5, 1);
TOSH_ASSIGN_PIN(SPI1_STE, 5, 0);

// P6
TOSH_ASSIGN_PIN(SDIO_DAT3, 6, 7);
TOSH_ASSIGN_PIN(SDIO_DAT2, 6, 6);
TOSH_ASSIGN_PIN(SDIO_DAT1, 6, 5);
TOSH_ASSIGN_PIN(GPS_ENABLE, 6, 4);
TOSH_ASSIGN_PIN(TILT_ENABLE, 6, 3);
TOSH_ASSIGN_PIN(FET_ENABLE, 6, 2);
TOSH_ASSIGN_PIN(PORT61, 6, 1);
TOSH_ASSIGN_PIN(PORT60, 6, 0);

// UART pin aliases
TOSH_ASSIGN_PIN(URXD1, 3, 7);
TOSH_ASSIGN_PIN(UTXD1, 3, 6);
TOSH_ASSIGN_PIN(URXD0, 3, 5);
TOSH_ASSIGN_PIN(UTXD0, 3, 4);
TOSH_ASSIGN_PIN(UCLK0, 3, 3);
TOSH_ASSIGN_PIN(SOMI0, 3, 2);
TOSH_ASSIGN_PIN(SIMO0, 3, 1);
TOSH_ASSIGN_PIN(UCLK1, 5, 3);
TOSH_ASSIGN_PIN(SOMI1, 5, 2);
TOSH_ASSIGN_PIN(SIMO1, 5, 1);

// need to undef atomic inside header files or nesC ignores the directive
#undef atomic

#endif // _H_hardware_h
