COMPONENT=TestPureTdmaC

	CFLAGS += -I$(UPMA_DIR)/chips/cc2420 \
		-I$(UPMA_DIR)/interfaces \
		-I$(UPMA_DIR)/lib/alarm \
		-I$(UPMA_DIR)/types \
		-I$(UPMA_DIR)/system \
		-I$(UPMA_DIR)/lib/macs/pure-tdma \
		-I$(UPMA_DIR)/lib/serial \
		-I$(UPMA_DIR)/platforms/$(PLATFORM) \
		-I$(TOSDIR)/lib/printf 
		
include $(MAKERULES)

