/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file implements the functions for encoding and decoding the
 * 'bigmsg_frame_part' message type. See bigmsg_frame_part.h for more details.
 */

#include <message.h>
#include "bigmsg_frame_part.h"

uint16_t bigmsg_frame_part_part_id_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 0, 16);
}

void bigmsg_frame_part_part_id_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 0, 16, value);
}

uint16_t bigmsg_frame_part_node_id_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 16, 16);
}

void bigmsg_frame_part_node_id_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 16, 16, value);
}

size_t bigmsg_frame_part_buf_offset(size_t index1)
{
  return bigmsg_frame_part_buf_offsetbits(index1) / 8;
}

uint8_t bigmsg_frame_part_buf_get(tmsg_t *msg, size_t index1)
{
  return tmsg_read_ube(msg, bigmsg_frame_part_buf_offsetbits(index1), 8);
}

void bigmsg_frame_part_buf_set(tmsg_t *msg, size_t index1, uint8_t value)
{
  tmsg_write_ube(msg, bigmsg_frame_part_buf_offsetbits(index1), 8, value);
}

size_t bigmsg_frame_part_buf_offsetbits(size_t index1)
{
  size_t offset = 32;
  if (index1 >= 64) { tmsg_fail(); return (size_t)-1; }
  offset += 0 + index1 * 8;
  return offset;
}

