COMPONENT=Figure8
CFLAGS += -I$(CTBTTOS)/platform/%p -I$(CTBTTOS)/interfaces -I$(CTBTTOS)/system -I$(CTBTTOS)/lib 
#-I$(TOSDIR)/platform/%p -I$(TOSDIR)/types -I$(TOSDIR)/system -I$(TOSDIR)/lib -I$(TOSDIR)/interfaces
#include ../Makerules
include $(MAKERULES)
