# the default timestamping precision is TMilli
# to set timestamping precision to 32kHz, uncomment the following line
# PFLAGS+=-DDFRF_32KHZ 

COMPONENT=BaseStationC
CFLAGS += -DCC2420_NO_ACKNOWLEDGEMENTS
CFLAGS += -DCC2420_NO_ADDRESS_RECOGNITION

include $(MAKERULES)

