TOSCONTRIB=/opt/tinyos-2.x-contrib
install:
	ln -sf $(TOSCONTRIB)/cedt/support/make/sim-energy.extra $(TOSROOT)/support/make/
	ln -sf $(TOSCONTRIB)/cedt/tos/platforms/mica2/sim $(TOSDIR)/platforms/mica2/

uninstall:
	rm -rf $(TOSDIR)/platforms/mica2/sim
	rm -rf $(TOSROOT)/support/make/sim-energy.extra


