#ifndef __APP_PROFILE_H
#define __APP_PROFILE_H

enum {
  RADIO_CHANNEL = 0x10,
  PAN_ID = 0x1234,
  COORDINATOR_ADDRESS = 0x0000,
  BEACON_ORDER = 6,
  SUPERFRAME_ORDER = 4,
  TX_POWER_BEACON = 0,
  TX_POWER = -20, // in dBm
};
#endif
